export const TASKS_DATA = [
    { Id: 1, Name: "Design Login Page", Description: "Create UI/UX design for login", Status: "Pending", EndDate: "2025-03-25", UserId: 1 },
    { Id: 2, Name: "Develop Authentication API", Description: "Implement JWT authentication", Status: "Completed", EndDate: "2025-03-10", UserId: 2 },
    { Id: 3, Name: "Database Schema Update", Description: "Modify user table to store profile picture", Status: "Pending", EndDate: "2025-04-05", UserId: 3 },
    { Id: 4, Name: "Optimize Performance", Description: "Improve API response time under 200ms", Status: "Pending", EndDate: "2025-03-30", UserId: 4 },
    { Id: 5, Name: "Create Reports Dashboard", Description: "Develop analytics dashboard for users", Status: "Completed", EndDate: "2025-03-15", UserId: 5 },
    { Id: 6, Name: "Fix Payment Gateway Bug", Description: "Resolve Stripe payment processing issue", Status: "Pending", EndDate: "2025-04-01", UserId: 6 },
    { Id: 7, Name: "Enhance Security Policies", Description: "Implement two-factor authentication", Status: "Pending", EndDate: "2025-03-28", UserId: 2 },
    { Id: 8, Name: "Write Unit Tests", Description: "Ensure 90% test coverage for modules", Status: "Pending", EndDate: "2025-04-02", UserId: 3 },
    { Id: 9, Name: "Deploy on Staging", Description: "Prepare and deploy the latest build", Status: "Completed", EndDate: "2025-03-18", UserId: 5 },
    { Id: 10, Name: "Update Documentation", Description: "Revise API documentation for latest version", Status: "Pending", EndDate: "2025-04-07", UserId: 1 },
    { Id: 11, Name: "User Role Management", Description: "Develop role-based access control", Status: "Completed", EndDate: "2025-03-12", UserId: 4 },
    { Id: 12, Name: "Refactor Codebase", Description: "Clean up redundant code and improve structure", Status: "Pending", EndDate: "2025-04-01", UserId: 6 },
    { Id: 13, Name: "Setup CI/CD Pipeline", Description: "Automate deployment process with GitHub Actions", Status: "Pending", EndDate: "2025-04-10", UserId: 3 },
    { Id: 14, Name: "Customer Feedback Form", Description: "Develop feedback collection form", Status: "Completed", EndDate: "2025-03-16", UserId: 1 },
    { Id: 15, Name: "Bug Fix: Session Timeout", Description: "Resolve auto logout issue on inactivity", Status: "Pending", EndDate: "2025-03-31", UserId: 5 },
    { Id: 16, Name: "Integrate Google Analytics", Description: "Track user behavior for better insights", Status: "Pending", EndDate: "2025-04-15", UserId: 2 },
    { Id: 17, Name: "Create Mobile App Wireframes", Description: "Design UI mockups for Android and iOS", Status: "Pending", EndDate: "2025-03-29", UserId: 4 },
    { Id: 18, Name: "Email Notification Service", Description: "Implement email alerts for user actions", Status: "Completed", EndDate: "2025-03-14", UserId: 6 },
    { Id: 19, Name: "Data Backup Strategy", Description: "Define and implement backup policies", Status: "Pending", EndDate: "2025-04-08", UserId: 3 },
    { Id: 20, Name: "Improve Accessibility", Description: "Ensure website meets WCAG standards", Status: "Pending", EndDate: "2025-03-27", UserId: 2 },
    { Id: 21, Name: "Optimize SQL Queries", Description: "Improve database query performance", Status: "Completed", EndDate: "2025-03-13", UserId: 5 },
    { Id: 22, Name: "Setup Redis Caching", Description: "Improve application speed using caching", Status: "Pending", EndDate: "2025-04-03", UserId: 1 },
    { Id: 23, Name: "Implement Dark Mode", Description: "Allow users to switch between themes", Status: "Pending", EndDate: "2025-04-12", UserId: 4 },
    { Id: 24, Name: "User Feedback Analysis", Description: "Analyze survey responses for improvements", Status: "Completed", EndDate: "2025-03-19", UserId: 6 },
    { Id: 25, Name: "Automate Server Scaling", Description: "Setup auto-scaling for cloud deployment", Status: "Pending", EndDate: "2025-04-06", UserId: 3 },
    { Id: 26, Name: "Enhance Search Functionality", Description: "Improve search accuracy and speed", Status: "Pending", EndDate: "2025-04-09", UserId: 2 },
    { Id: 27, Name: "Implement WebSockets", Description: "Enable real-time updates for notifications", Status: "Pending", EndDate: "2025-03-26", UserId: 1 },
    { Id: 28, Name: "Fix Mobile Layout Issues", Description: "Improve responsiveness on small screens", Status: "Completed", EndDate: "2025-03-17", UserId: 5 },
    { Id: 29, Name: "AI Chatbot Development", Description: "Build chatbot for automated customer support", Status: "Pending", EndDate: "2025-04-11", UserId: 6 },
    { Id: 30, Name: "Migrate to New Hosting", Description: "Move application to new cloud provider", Status: "Completed", EndDate: "2025-03-20", UserId: 4 }
];
